select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount) as revenue 
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest review rating
select item_purchased ,AVG(review_rating) 